// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-PMIuuI_a-R6Y9Ml00W6GGyfbSXYoC3I',
    appId: '1:361760513317:web:574167ff2952143f954ecc',
    messagingSenderId: '361760513317',
    projectId: 'vehiclebreakdownapplication',
    authDomain: 'vehiclebreakdownapplication.firebaseapp.com',
    storageBucket: 'vehiclebreakdownapplication.firebasestorage.app',
    measurementId: 'G-7KW6F7KE1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXlESx20VVcZ-CgQ7ElgxAatMiHDmk2Qo',
    appId: '1:361760513317:android:c6bc6bf99d44c7e3954ecc',
    messagingSenderId: '361760513317',
    projectId: 'vehiclebreakdownapplication',
    storageBucket: 'vehiclebreakdownapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDliEen8ek-Mw9MJe3dJqjtEmsVWrvw4Gw',
    appId: '1:361760513317:ios:3838ea60803e1bc3954ecc',
    messagingSenderId: '361760513317',
    projectId: 'vehiclebreakdownapplication',
    storageBucket: 'vehiclebreakdownapplication.firebasestorage.app',
    iosBundleId: 'com.sneha.vehiclebreakdown.vehicleBreakdown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDliEen8ek-Mw9MJe3dJqjtEmsVWrvw4Gw',
    appId: '1:361760513317:ios:3838ea60803e1bc3954ecc',
    messagingSenderId: '361760513317',
    projectId: 'vehiclebreakdownapplication',
    storageBucket: 'vehiclebreakdownapplication.firebasestorage.app',
    iosBundleId: 'com.sneha.vehiclebreakdown.vehicleBreakdown',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-PMIuuI_a-R6Y9Ml00W6GGyfbSXYoC3I',
    appId: '1:361760513317:web:490caba82b5b723b954ecc',
    messagingSenderId: '361760513317',
    projectId: 'vehiclebreakdownapplication',
    authDomain: 'vehiclebreakdownapplication.firebaseapp.com',
    storageBucket: 'vehiclebreakdownapplication.firebasestorage.app',
    measurementId: 'G-8TJ3QQJHKV',
  );
}
